name: Generate build version

on:
  push:
    tags:
      - 0.*
      - 1.*
  workflow_dispatch: {}

jobs:
  release:
    timeout-minutes: 90
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Install Dependencies
      run: |
        composer install -no
    - name: Build
      run: |
        composer run dist
    - name: Capture the toolkit build name/file
      run: |
        artifact_name=`ls dist/*.php | tr -d '\n'`
        echo "artifact_path=$artifact_name" >> $GITHUB_ENV
        echo "artifact_name=$(basename $artifact_name)" >> $GITHUB_ENV
    - name: Upload Built Toolkit
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.artifact_name }}
        path: ${{ env.artifact_path }}
    - name: Get the latest tag
      id: get_latest_tag
      run: |
        latest_tag=$(git describe --abbrev=0 --tags)
        echo "latest_tag=$latest_tag" >> $GITHUB_ENV
    - name: Add file to the latest tag
      uses: SierraSoftworks/gh-releases@v1.0.8
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        files: ${{ env.artifact_path }}
        overwrite: true
        release_tag: ${{ env.latest_tag }}
